[양동선] 3주차 과제 -ing
GDSC-Ewha-5th/GDSC-Server-5th pull request #30
Opened 2023-11-03 14:53 UTC by dongseon0

어제 시험이 끝나고 오늘 시작하여 아직 해결하지 못하여 과제 진행 중입니다. 죄송합니다.ㅠㅠ

2023-11-04 14:45 UTC, JeonHaeseung requested changes
남겨드린 코드 리뷰를 확인해주시고, 혹시 로드 리뷰 내용으로도 해결이 되지 않는다면 댓글 달아주세요!

2023-11-04 14:45 UTC, JeonHaeseung commented on 3주차 Server S-Day 과제/3주차 Server S-Day 과제.md
> +- 이런 것도 있구나. 맥이란 해도해도 신기해요! 언제쯤 맥OS를 점령할지...
귀엽다...🫶

2023-11-04 14:45 UTC, JeonHaeseung commented on 3주차 Server S-Day 과제/3주차 Server S-Day 과제.md
> +    implementation 'org.springframework.boot:spring-boot-starter-web'으로 수정하고 빌딩하고 실행!
`https://start.spring.io/` 웹사이트에서 종속성을 추가할 때, `Spring Web`으로 추가해주시면 된답니다!
물론 `build.grandle`에서 이렇게 직접 명시해서 종속성을 가져올 수도 있어요.

2023-11-04 14:45 UTC, JeonHaeseung commented on 3주차 Server S-Day 과제/3주차 Server S-Day 과제.md
> +- 참고 : https://devmango.tistory.com/97
이건 프론트엔드 코드(html)가 없어서 생긴 문제 같은데, 혹시 `resources` > `templates` 아래 경로에 html 파일들 다 넣어준 게 맞을까요? 아래 사진과 같은 경로에 넣어주셔야 해요!
![image](https://github.com/GDSC-Ewha-5th/GDSC-Server-5th/assets/89632139/ccd648ba-a26f-4dbe-9cd8-2c11ccfbf29c)

2023-11-04 14:45 UTC, JeonHaeseung commented on 3주차 Server S-Day 과제/3주차 Server S-Day 과제.md
> +SampleController.java 소스 코드 :
지금 소스 코드 자체는 제 프로젝트에 복사 붙여넣기 했을 때 아주 잘 돌아가요.
따라서 위에서 언급했듯이, html 파일들이 정확한 위치에 있는지 확인해주시고,
그리고 Thymeleaf 종속성을 제대로 추가해줬는지 확인해주세요.
![image](https://github.com/GDSC-Ewha-5th/GDSC-Server-5th/assets/89632139/247b872e-d852-47c5-a43e-39a1749ffea4)
이 종속성은 `build.gradle` 파일에서 다음 코드를 추가해주시면 됩니다.
`implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'`

2023-11-07 05:59 UTC, dongseon0 commented
문제 : 환경변수 설정을 했음에도 터미널에서 java -version을 입력할 경우 21버전으로 뜸.
해결 : jdk 21 제거

2023-11-07 06:05 UTC, JeonHaeseung approved these changes

2023-11-07 06:15 UTC, merged